# Generated by Django 4.2.7 on 2023-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeinventoryapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='runout_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='container',
            field=models.CharField(blank=True, default='armario abaixo da pia', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='expected_item_price_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
